//! do not edit this file
declare namespace NodeJS {
  interface ProcessEnv {
    DEV_MODE: boolean;
    DEBUG_MODE: boolean;
    MONGO_DB_URI: string;
    IMDB_KEY: string;
    REPORTS_CHANNEL_ID: string;
    FEEDBACK_CHANNEL_ID: string;
    GIPHY_API_KEY: string;
    ERRORLOGS_CHANNEL_ID: string;
    ALEXFLIPNOTE_API_KEY: string;
    BUG_REPORTS_CHANNEL_ID: string;
    OPEN_WEATHER_MAP_API_KEY: string;
    PASTE_CLIENT_KEY: string;
    DASHBOARD_ENABLED: boolean;
    NEXT_PUBLIC_DASHBOARD_BOTNAME: string;
    NEXT_PUBLIC_DASHBOARD_URL: string;
    DASHBOARD_DISCORD_API_URL: string;
    DASHBOARD_JWT_SECRET: string;
    DASHBOARD_CALLBACK_URL: string;
    DASHBOARD_PORT: number;
    DISCORD_BOT_TOKEN: string;
    DISCORD_CLIENT_ID: string;
    DISCORD_CLIENT_SECRET: string;
    OWNERS: string[];
  }
}